- name: "Query for existing NAT gateway(s)"
  ec2_vpc_nat_gateway_info:
    region: "{{ vpc.aws_vpc_region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
  register: nat_gateways

- name: "Delete the nat gateways and release the EIPs"
  ec2_vpc_nat_gateway:
    region: "{{ vpc.aws_vpc_region }}"
    nat_gateway_id: "{{ item.nat_gateway_id }}"
    release_eip: yes 
    state: "absent"
    wait: yes
    wait_timeout: 300
  with_items: "{{ nat_gateways.result }}"
  ignore_errors: true
