- name: "Query for existing route table(s)"
  ec2_vpc_route_table_info:
    region: "{{ vpc.aws_vpc_region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
      association.main: "false"
  register: route_table_info

- set_fact:
    route_tables_to_delete: "{{ (route_tables_to_delete | default([])) + [item.id] }}"
  when: item.associations | length == 0 or not item.associations[0].main
  loop: "{{ route_table_info.route_tables }}"

- pause: seconds=30

- name: "Purge routes"
  ec2_vpc_route_table:
    region: "{{ vpc.aws_vpc_region }}"
    vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
    route_table_id: "{{ item }}"
    lookup: "id"
    purge_routes: "yes"
    purge_subnets: "yes"
    state: "present"
  loop: "{{ route_tables_to_delete }}"
  when: route_tables_to_delete is defined

- pause: seconds=30

- name: "Delete route table"
  ec2_vpc_route_table:
    region: "{{ vpc.aws_vpc_region }}"
    vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
    route_table_id: "{{ item }}"
    lookup: "id"
    state: "absent"
  loop: "{{ route_tables_to_delete }}"
  when: route_tables_to_delete is defined
